export type IndonesianCity = { city: string; province: string };

export const indonesianCities: IndonesianCity[] = [{"city":"Aceh Barat","province":"Aceh"},
{"city":"Aceh Barat Daya","province":"Aceh"},
{"city":"Aceh Besar","province":"Aceh"},
{"city":"Aceh Jaya","province":"Aceh"},
{"city":"Aceh Selatan","province":"Aceh"},
{"city":"Aceh Singkil","province":"Aceh"},
{"city":"Aceh Tamiang","province":"Aceh"},
{"city":"Aceh Tengah","province":"Aceh"},
{"city":"Aceh Tenggara","province":"Aceh"},
{"city":"Aceh Timur","province":"Aceh"},
{"city":"Aceh Utara","province":"Aceh"},
{"city":"Agam","province":"Sumatera Barat"},
{"city":"Alor","province":"Nusa Tenggara Timur"},
{"city":"Ambon","province":"Maluku"},
{"city":"Asahan","province":"Sumatera Utara"},
{"city":"Asmat","province":"Papua"},
{"city":"Badung","province":"Bali"},
{"city":"Balangan","province":"Kalimantan Selatan"},
{"city":"Balikpapan","province":"Kalimantan Timur"},
{"city":"Banda Aceh","province":"Aceh"},
{"city":"Bandar Lampung","province":"Lampung"},
{"city":"Bandung","province":"Jawa Barat"},
{"city":"Bandung Barat","province":"Jawa Barat"},
{"city":"Banggai","province":"Sulawesi Tengah"},
{"city":"Banggai Kepulauan","province":"Sulawesi Tengah"},
{"city":"Bangka","province":"Kepulauan Bangka Belitung"},
{"city":"Bangka Barat","province":"Kepulauan Bangka Belitung"},
{"city":"Bangka Selatan","province":"Kepulauan Bangka Belitung"},
{"city":"Bangka Tengah","province":"Kepulauan Bangka Belitung"},
{"city":"Bangkalan","province":"Jawa Timur"},
{"city":"Bangli","province":"Bali"},
{"city":"Kabupaten Banjar","province":"Kalimantan Selatan"},
{"city":"Kota Banjar","province":"Jawa Barat"},
{"city":"Banjar Baru","province":"Kalimantan Selatan"},
{"city":"Banjarmasin","province":"Kalimantan Selatan"},
{"city":"Banjarnegara","province":"Jawa Tengah"},
{"city":"Bantaeng","province":"Sulawesi Selatan"},
{"city":"Bantul","province":"Yogyakarta"},
{"city":"Banyu Asin","province":"Sumatera Selatan"},
{"city":"Banyumas","province":"Jawa Tengah"},
{"city":"Banyuwangi","province":"Jawa Timur"},
{"city":"Barito Kuala","province":"Kalimantan Selatan"},
{"city":"Barito Selatan","province":"Kalimantan Tengah"},
{"city":"Barito Timur","province":"Kalimantan Tengah"},
{"city":"Barito Utara","province":"Kalimantan Tengah"},
{"city":"Barru","province":"Sulawesi Selatan"},
{"city":"Batam","province":"Kepulauan Riau"},
{"city":"Batang","province":"Jawa Tengah"},
{"city":"Batang Hari","province":"Jambi"},
{"city":"Batu","province":"Jawa Timur"},
{"city":"Batu Bara","province":"Sumatera Utara"},
{"city":"Baubau","province":"Sulawesi Tenggara"},
{"city":"Bekasi","province":"Jawa Barat"},
{"city":"Belitung","province":"Kepulauan Bangka Belitung"},
{"city":"Belitung Timur","province":"Kepulauan Bangka Belitung"},
{"city":"Belu","province":"Nusa Tenggara Timur"},
{"city":"Bener Meriah","province":"Aceh"},
{"city":"Bengkalis","province":"Riau"},
{"city":"Bengkayang","province":"Kalimantan Barat"},
{"city":"Bengkulu","province":"Bengkulu"},
{"city":"Bengkulu Selatan","province":"Bengkulu"},
{"city":"Bengkulu Tengah","province":"Bengkulu"},
{"city":"Bengkulu Utara","province":"Bengkulu"},
{"city":"Berau","province":"Kalimantan Timur"},
{"city":"Biak Numfor","province":"Papua"},
{"city":"Bima","province":"Nusa Tenggara Barat"},
{"city":"Binjai","province":"Sumatera Utara"},
{"city":"Bintan","province":"Kepulauan Riau"},
{"city":"Bireuen","province":"Aceh"},
{"city":"Bitung","province":"Sulawesi Utara"},
{"city":"Blitar","province":"Jawa Timur"},
{"city":"Blora","province":"Jawa Tengah"},
{"city":"Boalemo","province":"Gorontalo"},
{"city":"Bogor","province":"Jawa Barat"},
{"city":"Bojonegoro","province":"Jawa Timur"},
{"city":"Bolaang Mongondow","province":"Sulawesi Utara"},
{"city":"Bolaang Mongondow Selatan","province":"Sulawesi Utara"},
{"city":"Bolaang Mongondow Timur","province":"Sulawesi Utara"},
{"city":"Bolaang Mongondow Utara","province":"Sulawesi Utara"},
{"city":"Bombana","province":"Sulawesi Tenggara"},
{"city":"Bondowoso","province":"Jawa Timur"},
{"city":"Bone","province":"Sulawesi Selatan"},
{"city":"Bone Bolango","province":"Gorontalo"},
{"city":"Bontang","province":"Kalimantan Timur"},
{"city":"Boven Digoel","province":"Papua"},
{"city":"Boyolali","province":"Jawa Tengah"},
{"city":"Brebes","province":"Jawa Tengah"},
{"city":"Bukittinggi","province":"Sumatera Barat"},
{"city":"Buleleng","province":"Bali"},
{"city":"Bulukumba","province":"Sulawesi Selatan"},
{"city":"Bulungan","province":"Kalimantan Utara"},
{"city":"Bungo","province":"Jambi"},
{"city":"Buol","province":"Sulawesi Tengah"},
{"city":"Buru","province":"Maluku"},
{"city":"Buru Selatan","province":"Maluku"},
{"city":"Buton","province":"Sulawesi Tenggara"},
{"city":"Buton Utara","province":"Sulawesi Tenggara"},
{"city":"Ciamis","province":"Jawa Barat"},
{"city":"Cianjur","province":"Jawa Barat"},
{"city":"Cilacap","province":"Jawa Tengah"},
{"city":"Cilegon","province":"Banten"},
{"city":"Cimahi","province":"Jawa Barat"},
{"city":"Cirebon","province":"Jawa Barat"},
{"city":"Dairi","province":"Sumatera Utara"},
{"city":"Deiyai","province":"Papua"},
{"city":"Deli Serdang","province":"Sumatera Utara"},
{"city":"Demak","province":"Jawa Tengah"},
{"city":"Denpasar","province":"Bali"},
{"city":"Depok","province":"Jawa Barat"},
{"city":"Dharmasraya","province":"Sumatera Barat"},
{"city":"Dogiyai","province":"Papua"},
{"city":"Dompu","province":"Nusa Tenggara Barat"},
{"city":"Donggala","province":"Sulawesi Tengah"},
{"city":"Dumai","province":"Riau"},
{"city":"Empat Lawang","province":"Sumatera Selatan"},
{"city":"Ende","province":"Nusa Tenggara Timur"},
{"city":"Enrekang","province":"Sulawesi Selatan"},
{"city":"Fakfak","province":"Papua Barat"},
{"city":"Flores Timur","province":"Nusa Tenggara Timur"},
{"city":"Garut","province":"Jawa Barat"},
{"city":"Gayo Lues","province":"Aceh"},
{"city":"Gianyar","province":"Bali"},
{"city":"Gorontalo","province":"Gorontalo"},
{"city":"Gorontalo Utara","province":"Gorontalo"},
{"city":"Gowa","province":"Sulawesi Selatan"},
{"city":"Gresik","province":"Jawa Timur"},
{"city":"Grobogan","province":"Jawa Tengah"},
{"city":"Gunung Kidul","province":"Yogyakarta"},
{"city":"Gunung Mas","province":"Kalimantan Tengah"},
{"city":"Gunungsitoli","province":"Sumatera Utara"},
{"city":"Halmahera Barat","province":"Maluku Utara"},
{"city":"Halmahera Selatan","province":"Maluku Utara"},
{"city":"Halmahera Tengah","province":"Maluku Utara"},
{"city":"Halmahera Timur","province":"Maluku Utara"},
{"city":"Halmahera Utara","province":"Maluku Utara"},
{"city":"Hulu Sungai Selatan","province":"Kalimantan Selatan"},
{"city":"Hulu Sungai Tengah","province":"Kalimantan Selatan"},
{"city":"Hulu Sungai Utara","province":"Kalimantan Selatan"},
{"city":"Humbang Hasundutan","province":"Sumatera Utara"},
{"city":"Indragiri Hilir","province":"Riau"},
{"city":"Indragiri Hulu","province":"Riau"},
{"city":"Indramayu","province":"Jawa Barat"},
{"city":"Intan Jaya","province":"Papua"},
{"city":"Jakarta Barat","province":"DKI Jakarta"},
{"city":"Jakarta Pusat","province":"DKI Jakarta"},
{"city":"Jakarta Selatan","province":"DKI Jakarta"},
{"city":"Jakarta Timur","province":"DKI Jakarta"},
{"city":"Jakarta Utara","province":"DKI Jakarta"},
{"city":"Jambi","province":"Jambi"},
{"city":"Jayapura","province":"Papua"},
{"city":"Jayawijaya","province":"Papua"},
{"city":"Jember","province":"Jawa Timur"},
{"city":"Jembrana","province":"Bali"},
{"city":"Jeneponto","province":"Sulawesi Selatan"},
{"city":"Jepara","province":"Jawa Tengah"},
{"city":"Jombang","province":"Jawa Timur"},
{"city":"Kaimana","province":"Papua Barat"},
{"city":"Kampar","province":"Riau"},
{"city":"Kapuas","province":"Kalimantan Tengah"},
{"city":"Kapuas Hulu","province":"Kalimantan Barat"},
{"city":"Karang Asem","province":"Bali"},
{"city":"Karanganyar","province":"Jawa Tengah"},
{"city":"Karawang","province":"Jawa Barat"},
{"city":"Karimun","province":"Kepulauan Riau"},
{"city":"Karo","province":"Sumatera Utara"},
{"city":"Katingan","province":"Kalimantan Tengah"},
{"city":"Kaur","province":"Bengkulu"},
{"city":"Kayong Utara","province":"Kalimantan Barat"},
{"city":"Kebumen","province":"Jawa Tengah"},
{"city":"Kediri","province":"Jawa Timur"},
{"city":"Keerom","province":"Papua"},
{"city":"Kendal","province":"Jawa Tengah"},
{"city":"Kendari","province":"Sulawesi Tenggara"},
{"city":"Kepahiang","province":"Bengkulu"},
{"city":"Kepulauan Anambas","province":"Kepulauan Riau"},
{"city":"Kepulauan Aru","province":"Maluku"},
{"city":"Kepulauan Mentawai","province":"Sumatera Barat"},
{"city":"Kepulauan Meranti","province":"Riau"},
{"city":"Kepulauan Sangihe","province":"Sulawesi Utara"},
{"city":"Kepulauan Selayar","province":"Sulawesi Selatan"},
{"city":"Kepulauan Seribu","province":"DKI Jakarta"},
{"city":"Kepulauan Sula","province":"Maluku Utara"},
{"city":"Kepulauan Talaud","province":"Sulawesi Utara"},
{"city":"Kepulauan Yapen","province":"Papua"},
{"city":"Kerinci","province":"Jambi"},
{"city":"Ketapang","province":"Kalimantan Barat"},
{"city":"Klaten","province":"Jawa Tengah"},
{"city":"Klungkung","province":"Bali"},
{"city":"Kolaka","province":"Sulawesi Tenggara"},
{"city":"Kolaka Utara","province":"Sulawesi Tenggara"},
{"city":"Konawe","province":"Sulawesi Tenggara"},
{"city":"Konawe Selatan","province":"Sulawesi Tenggara"},
{"city":"Konawe Utara","province":"Sulawesi Tenggara"},
{"city":"Kotamobagu","province":"Sulawesi Utara"},
{"city":"Kotawaringin Barat","province":"Kalimantan Tengah"},
{"city":"Kotawaringin Timur","province":"Kalimantan Tengah"},
{"city":"Kuantan Singingi","province":"Riau"},
{"city":"Kubu Raya","province":"Kalimantan Barat"},
{"city":"Kudus","province":"Jawa Tengah"},
{"city":"Kulon Progo","province":"Yogyakarta"},
{"city":"Kuningan","province":"Jawa Barat"},
{"city":"Kupang","province":"Nusa Tenggara Timur"},
{"city":"Kutai Barat","province":"Kalimantan Timur"},
{"city":"Kutai Kartanegara","province":"Kalimantan Timur"},
{"city":"Kutai Timur","province":"Kalimantan Timur"},
{"city":"Labuhan Batu","province":"Sumatera Utara"},
{"city":"Labuhan Batu Selatan","province":"Sumatera Utara"},
{"city":"Labuhan Batu Utara","province":"Sumatera Utara"},
{"city":"Lahat","province":"Sumatera Selatan"},
{"city":"Lamandau","province":"Kalimantan Tengah"},
{"city":"Lamongan","province":"Jawa Timur"},
{"city":"Lampung Barat","province":"Lampung"},
{"city":"Lampung Selatan","province":"Lampung"},
{"city":"Lampung Tengah","province":"Lampung"},
{"city":"Lampung Timur","province":"Lampung"},
{"city":"Lampung Utara","province":"Lampung"},
{"city":"Landak","province":"Kalimantan Barat"},
{"city":"Langkat","province":"Sumatera Utara"},
{"city":"Langsa","province":"Aceh"},
{"city":"Lanny Jaya","province":"Papua"},
{"city":"Lebak","province":"Banten"},
{"city":"Lebong","province":"Bengkulu"},
{"city":"Lembata","province":"Nusa Tenggara Timur"},
{"city":"Lhokseumawe","province":"Aceh"},
{"city":"Lima Puluh Kota","province":"Sumatera Barat"},
{"city":"Lingga","province":"Kepulauan Riau"},
{"city":"Lombok Barat","province":"Nusa Tenggara Barat"},
{"city":"Lombok Tengah","province":"Nusa Tenggara Barat"},
{"city":"Lombok Timur","province":"Nusa Tenggara Barat"},
{"city":"Lombok Utara","province":"Nusa Tenggara Barat"},
{"city":"Lubuklinggau","province":"Sumatera Selatan"},
{"city":"Lumajang","province":"Jawa Timur"},
{"city":"Luwu","province":"Sulawesi Selatan"},
{"city":"Luwu Timur","province":"Sulawesi Selatan"},
{"city":"Luwu Utara","province":"Sulawesi Selatan"},
{"city":"Madiun","province":"Jawa Timur"},
{"city":"Magelang","province":"Jawa Tengah"},
{"city":"Magetan","province":"Jawa Timur"},
{"city":"Majalengka","province":"Jawa Barat"},
{"city":"Majene","province":"Sulawesi Barat"},
{"city":"Makassar","province":"Sulawesi Selatan"},
{"city":"Malang","province":"Jawa Timur"},
{"city":"Malinau","province":"Kalimantan Utara"},
{"city":"Maluku Barat Daya","province":"Maluku"},
{"city":"Maluku Tengah","province":"Maluku"},
{"city":"Maluku Tenggara","province":"Maluku"},
{"city":"Maluku Tenggara Barat","province":"Maluku"},
{"city":"Mamasa","province":"Sulawesi Barat"},
{"city":"Mamberamo Raya","province":"Papua"},
{"city":"Mamberamo Tengah","province":"Papua"},
{"city":"Mamuju","province":"Sulawesi Barat"},
{"city":"Mamuju Utara","province":"Sulawesi Barat"},
{"city":"Manado","province":"Sulawesi Utara"},
{"city":"Mandailing Natal","province":"Sumatera Utara"},
{"city":"Manggarai","province":"Nusa Tenggara Timur"},
{"city":"Manggarai Barat","province":"Nusa Tenggara Timur"},
{"city":"Manggarai Timur","province":"Nusa Tenggara Timur"},
{"city":"Manokwari","province":"Papua Barat"},
{"city":"Mappi","province":"Papua"},
{"city":"Maros","province":"Sulawesi Selatan"},
{"city":"Mataram","province":"Nusa Tenggara Barat"},
{"city":"Maybrat","province":"Papua Barat"},
{"city":"Medan","province":"Sumatera Utara"},
{"city":"Melawi","province":"Kalimantan Barat"},
{"city":"Merangin","province":"Jambi"},
{"city":"Merauke","province":"Papua"},
{"city":"Mesuji","province":"Lampung"},
{"city":"Metro","province":"Lampung"},
{"city":"Mimika","province":"Papua"},
{"city":"Minahasa","province":"Sulawesi Utara"},
{"city":"Minahasa Selatan","province":"Sulawesi Utara"},
{"city":"Minahasa Tenggara","province":"Sulawesi Utara"},
{"city":"Minahasa Utara","province":"Sulawesi Utara"},
{"city":"Mojokerto","province":"Jawa Timur"},
{"city":"Morowali","province":"Sulawesi Tengah"},
{"city":"Muara Enim","province":"Sumatera Selatan"},
{"city":"Muaro Jambi","province":"Jambi"},
{"city":"Mukomuko","province":"Bengkulu"},
{"city":"Muna","province":"Sulawesi Tenggara"},
{"city":"Murung Raya","province":"Kalimantan Tengah"},
{"city":"Musi Banyuasin","province":"Sumatera Selatan"},
{"city":"Musi Rawas","province":"Sumatera Selatan"},
{"city":"Nabire","province":"Papua"},
{"city":"Nagan Raya","province":"Aceh"},
{"city":"Nagekeo","province":"Nusa Tenggara Timur"},
{"city":"Natuna","province":"Kepulauan Riau"},
{"city":"Nduga","province":"Papua"},
{"city":"Ngada","province":"Nusa Tenggara Timur"},
{"city":"Nganjuk","province":"Jawa Timur"},
{"city":"Ngawi","province":"Jawa Timur"},
{"city":"Nias","province":"Sumatera Utara"},
{"city":"Nias Barat","province":"Sumatera Utara"},
{"city":"Nias Selatan","province":"Sumatera Utara"},
{"city":"Nias Utara","province":"Sumatera Utara"},
{"city":"Nunukan","province":"Kalimantan Utara"},
{"city":"Ogan Ilir","province":"Sumatera Selatan"},
{"city":"Ogan Komering Ilir","province":"Sumatera Selatan"},
{"city":"Ogan Komering Ulu","province":"Sumatera Selatan"},
{"city":"Ogan Komering Ulu Selatan","province":"Sumatera Selatan"},
{"city":"Ogan Komering Ulu Timur","province":"Sumatera Selatan"},
{"city":"Pacitan","province":"Jawa Timur"},
{"city":"Padang","province":"Sumatera Barat"},
{"city":"Padang Lawas","province":"Sumatera Utara"},
{"city":"Padang Lawas Utara","province":"Sumatera Utara"},
{"city":"Padang Panjang","province":"Sumatera Barat"},
{"city":"Padang Pariaman","province":"Sumatera Barat"},
{"city":"Padangsidimpuan","province":"Sumatera Utara"},
{"city":"Pagar Alam","province":"Sumatera Selatan"},
{"city":"Pakpak Bharat","province":"Sumatera Utara"},
{"city":"Palangka Raya","province":"Kalimantan Tengah"},
{"city":"Palembang","province":"Sumatera Selatan"},
{"city":"Palopo","province":"Sulawesi Selatan"},
{"city":"Palu","province":"Sulawesi Tengah"},
{"city":"Pamekasan","province":"Jawa Timur"},
{"city":"Pandeglang","province":"Banten"},
{"city":"Pangandaran","province":"Jawa Barat"},
{"city":"Pangkajene Dan Kepulauan","province":"Sulawesi Selatan"},
{"city":"Pangkal Pinang","province":"Kepulauan Bangka Belitung"},
{"city":"Paniai","province":"Papua"},
{"city":"Parepare","province":"Sulawesi Selatan"},
{"city":"Pariaman","province":"Sumatera Barat"},
{"city":"Parigi Moutong","province":"Sulawesi Tengah"},
{"city":"Pasaman","province":"Sumatera Barat"},
{"city":"Pasaman Barat","province":"Sumatera Barat"},
{"city":"Paser","province":"Kalimantan Timur"},
{"city":"Pasuruan","province":"Jawa Timur"},
{"city":"Pati","province":"Jawa Tengah"},
{"city":"Payakumbuh","province":"Sumatera Barat"},
{"city":"Pegunungan Bintang","province":"Papua"},
{"city":"Pekalongan","province":"Jawa Tengah"},
{"city":"Pekanbaru","province":"Riau"},
{"city":"Pelalawan","province":"Riau"},
{"city":"Pemalang","province":"Jawa Tengah"},
{"city":"Pematang Siantar","province":"Sumatera Utara"},
{"city":"Penajam Paser Utara","province":"Kalimantan Timur"},
{"city":"Pesawaran","province":"Lampung"},
{"city":"Pesisir Barat","province":"Lampung"},
{"city":"Pesisir Selatan","province":"Sumatera Barat"},
{"city":"Pidie","province":"Aceh"},
{"city":"Pidie Jaya","province":"Aceh"},
{"city":"Pinrang","province":"Sulawesi Selatan"},
{"city":"Pohuwato","province":"Gorontalo"},
{"city":"Polewali Mandar","province":"Sulawesi Barat"},
{"city":"Ponorogo","province":"Jawa Timur"},
{"city":"Pontianak","province":"Kalimantan Barat"},
{"city":"Poso","province":"Sulawesi Tengah"},
{"city":"Prabumulih","province":"Sumatera Selatan"},
{"city":"Pringsewu","province":"Lampung"},
{"city":"Probolinggo","province":"Jawa Timur"},
{"city":"Pulang Pisau","province":"Kalimantan Tengah"},
{"city":"Pulau Morotai","province":"Maluku Utara"},
{"city":"Puncak","province":"Papua"},
{"city":"Puncak Jaya","province":"Papua"},
{"city":"Purbalingga","province":"Jawa Tengah"},
{"city":"Purwakarta","province":"Jawa Barat"},
{"city":"Purworejo","province":"Jawa Tengah"},
{"city":"Raja Ampat","province":"Papua Barat"},
{"city":"Rejang Lebong","province":"Bengkulu"},
{"city":"Rembang","province":"Jawa Tengah"},
{"city":"Rokan Hilir","province":"Riau"},
{"city":"Rokan Hulu","province":"Riau"},
{"city":"Rote Ndao","province":"Nusa Tenggara Timur"},
{"city":"Sabang","province":"Aceh"},
{"city":"Sabu Raijua","province":"Nusa Tenggara Timur"},
{"city":"Salatiga","province":"Jawa Tengah"},
{"city":"Samarinda","province":"Kalimantan Timur"},
{"city":"Sambas","province":"Kalimantan Barat"},
{"city":"Samosir","province":"Sumatera Utara"},
{"city":"Sampang","province":"Jawa Timur"},
{"city":"Sanggau","province":"Kalimantan Barat"},
{"city":"Sarmi","province":"Papua"},
{"city":"Sarolangun","province":"Jambi"},
{"city":"Sawah Lunto","province":"Sumatera Barat"},
{"city":"Sekadau","province":"Kalimantan Barat"},
{"city":"Seluma","province":"Bengkulu"},
{"city":"Semarang","province":"Jawa Tengah"},
{"city":"Seram Bagian Barat","province":"Maluku"},
{"city":"Seram Bagian Timur","province":"Maluku"},
{"city":"Serang","province":"Banten"},
{"city":"Serdang Bedagai","province":"Sumatera Utara"},
{"city":"Seruyan","province":"Kalimantan Tengah"},
{"city":"Siak","province":"Riau"},
{"city":"Siau Tagulandang Biaro","province":"Sulawesi Utara"},
{"city":"Sibolga","province":"Sumatera Utara"},
{"city":"Sidenreng Rappang","province":"Sulawesi Selatan"},
{"city":"Sidoarjo","province":"Jawa Timur"},
{"city":"Sigi","province":"Sulawesi Tengah"},
{"city":"Sijunjung","province":"Sumatera Barat"},
{"city":"Sikka","province":"Nusa Tenggara Timur"},
{"city":"Simalungun","province":"Sumatera Utara"},
{"city":"Simeulue","province":"Aceh"},
{"city":"Singkawang","province":"Kalimantan Barat"},
{"city":"Sinjai","province":"Sulawesi Selatan"},
{"city":"Sintang","province":"Kalimantan Barat"},
{"city":"Situbondo","province":"Jawa Timur"},
{"city":"Sleman","province":"Yogyakarta"},
{"city":"Solok","province":"Sumatera Barat"},
{"city":"Solok Selatan","province":"Sumatera Barat"},
{"city":"Soppeng","province":"Sulawesi Selatan"},
{"city":"Sorong","province":"Papua Barat"},
{"city":"Sorong Selatan","province":"Papua Barat"},
{"city":"Sragen","province":"Jawa Tengah"},
{"city":"Subang","province":"Jawa Barat"},
{"city":"Subulussalam","province":"Aceh"},
{"city":"Sukabumi","province":"Jawa Barat"},
{"city":"Sukamara","province":"Kalimantan Tengah"},
{"city":"Sukoharjo","province":"Jawa Tengah"},
{"city":"Sumba Barat","province":"Nusa Tenggara Timur"},
{"city":"Sumba Barat Daya","province":"Nusa Tenggara Timur"},
{"city":"Sumba Tengah","province":"Nusa Tenggara Timur"},
{"city":"Sumba Timur","province":"Nusa Tenggara Timur"},
{"city":"Sumbawa","province":"Nusa Tenggara Barat"},
{"city":"Sumbawa Barat","province":"Nusa Tenggara Barat"},
{"city":"Sumedang","province":"Jawa Barat"},
{"city":"Sumenep","province":"Jawa Timur"},
{"city":"Sungai Penuh","province":"Jambi"},
{"city":"Supiori","province":"Papua"},
{"city":"Surabaya","province":"Jawa Timur"},
{"city":"Surakarta","province":"Jawa Tengah"},
{"city":"Tabalong","province":"Kalimantan Selatan"},
{"city":"Tabanan","province":"Bali"},
{"city":"Takalar","province":"Sulawesi Selatan"},
{"city":"Tambrauw","province":"Papua Barat"},
{"city":"Tana Tidung","province":"Kalimantan Utara"},
{"city":"Tana Toraja","province":"Sulawesi Selatan"},
{"city":"Tanah Bumbu","province":"Kalimantan Selatan"},
{"city":"Tanah Datar","province":"Sumatera Barat"},
{"city":"Tanah Laut","province":"Kalimantan Selatan"},
{"city":"Tangerang","province":"Banten"},
{"city":"Tangerang Selatan","province":"Banten"},
{"city":"Tanggamus","province":"Lampung"},
{"city":"Tanjung Balai","province":"Sumatera Utara"},
{"city":"Tanjung Jabung Barat","province":"Jambi"},
{"city":"Tanjung Jabung Timur","province":"Jambi"},
{"city":"Tanjung Pinang","province":"Kepulauan Riau"},
{"city":"Tapanuli Selatan","province":"Sumatera Utara"},
{"city":"Tapanuli Tengah","province":"Sumatera Utara"},
{"city":"Tapanuli Utara","province":"Sumatera Utara"},
{"city":"Tapin","province":"Kalimantan Selatan"},
{"city":"Tarakan","province":"Kalimantan Utara"},
{"city":"Tasikmalaya","province":"Jawa Barat"},
{"city":"Tebing Tinggi","province":"Sumatera Utara"},
{"city":"Tebo","province":"Jambi"},
{"city":"Tegal","province":"Jawa Tengah"},
{"city":"Teluk Bintuni","province":"Papua Barat"},
{"city":"Teluk Wondama","province":"Papua Barat"},
{"city":"Temanggung","province":"Jawa Tengah"},
{"city":"Ternate","province":"Maluku Utara"},
{"city":"Tidore Kepulauan","province":"Maluku Utara"},
{"city":"Timor Tengah Selatan","province":"Nusa Tenggara Timur"},
{"city":"Timor Tengah Utara","province":"Nusa Tenggara Timur"},
{"city":"Toba Samosir","province":"Sumatera Utara"},
{"city":"Tojo Una-una","province":"Sulawesi Tengah"},
{"city":"Toli-toli","province":"Sulawesi Tengah"},
{"city":"Tolikara","province":"Papua"},
{"city":"Tomohon","province":"Sulawesi Utara"},
{"city":"Toraja Utara","province":"Sulawesi Selatan"},
{"city":"Trenggalek","province":"Jawa Timur"},
{"city":"Tual","province":"Maluku"},
{"city":"Tuban","province":"Jawa Timur"},
{"city":"Tulang Bawang Barat","province":"Lampung"},
{"city":"Tulangbawang","province":"Lampung"},
{"city":"Tulungagung","province":"Jawa Timur"},
{"city":"Wajo","province":"Sulawesi Selatan"},
{"city":"Wakatobi","province":"Sulawesi Tenggara"},
{"city":"Waropen","province":"Papua"},
{"city":"Way Kanan","province":"Lampung"},
{"city":"Wonogiri","province":"Jawa Tengah"},
{"city":"Wonosobo","province":"Jawa Tengah"},
{"city":"Yahukimo","province":"Papua"},
{"city":"Yalimo","province":"Papua"},
{"city":"Yogyakarta","province":"Yogyakarta"}];
export const cityProvinceByName = new Map(indonesianCities.map((item) => [item.city.toLocaleLowerCase("id-ID"), item.province]));
