export type Mode = "lelang" | "langsung" | "terjual";
export type Property = { id: number; mode: Mode; type: string; title: string; city: string; land: number; build: number; beds: number; price: number; bid?: number; bidders?: number; duration?: number; desc: string; imageUrl?: string; imageUrls?: string[]; createdAt?: string };

export const seedProperties: Property[] = [
  {id:1, mode:'lelang', type:'Rumah', title:'Rumah 2 Lantai Sawojajar', city:'Malang, Jawa Timur', land:120, build:150, beds:4, price:850000000, bid:790000000, bidders:14, duration: 53, desc:'Rumah dua lantai siap huni di kawasan Sawojajar, dekat sekolah dan pasar tradisional. Sertifikat Hak Milik, lelang atas permintaan bank.'},
  {id:2, mode:'langsung', type:'Tanah', title:'Tanah Kavling Siap Bangun Batu', city:'Batu, Jawa Timur', land:300, build:0, beds:0, price:450000000, desc:'Tanah kavling view pegunungan, akses jalan aspal 6 meter, cocok untuk hunian atau villa. SHM atas nama sendiri.'},
  {id:3, mode:'lelang', type:'Apartemen', title:'Apartemen Studio Green Bay', city:'Pluit, Jakarta Utara', land:0, build:32, beds:1, price:520000000, bid:495000000, bidders:9, duration: 18, desc:'Unit studio lantai 12 menghadap kolam renang, furnished sebagian. Cocok untuk investasi sewa harian.'},
  {id:4, mode:'langsung', type:'Ruko', title:'Ruko 3 Lantai Jalan Soekarno-Hatta', city:'Malang, Jawa Timur', land:90, build:220, beds:0, price:2100000000, desc:'Ruko strategis di jalur utama kampus, cocok untuk kos-kosan, kantor, atau F&B. Bebas banjir, listrik 5500 VA.'},
  {id:5, mode:'lelang', type:'Tanah', title:'Tanah Sawah Produktif Kepanjen', city:'Kepanjen, Jawa Timur', land:5000, build:0, beds:0, price:1200000000, bid:1050000000, bidders:6, duration: 98, desc:'Lahan sawah aktif dengan akses irigasi teknis, dekat rencana jalan tol. Lelang eksekusi hak tanggungan.'},
  {id:6, mode:'langsung', type:'Villa', title:'Villa Pemandangan Sawah Ubud', city:'Ubud, Bali', land:400, build:180, beds:3, price:3800000000, desc:'Villa tropis tiga kamar dengan kolam renang privat, kontrak leasehold 25 tahun, menghadap terasering sawah.'},
  {id:7, mode:'terjual', type:'Rumah', title:'Rumah Minimalis Perumahan Araya', city:'Malang, Jawa Timur', land:105, build:90, beds:3, price:980000000, desc:'Rumah dalam kompleks berpagar dengan keamanan 24 jam, sudah terjual melalui lelang bulan lalu.'},
  {id:8, mode:'lelang', type:'Gudang', title:'Gudang Logistik Rungkut', city:'Surabaya, Jawa Timur', land:1500, build:1100, beds:0, price:4200000000, bid:3900000000, bidders:5, duration: 33, desc:'Gudang dengan akses truk kontainer, ketinggian plafon 9 meter, dekat pelabuhan Tanjung Perak.'},
  {id:9, mode:'langsung', type:'Apartemen', title:'Apartemen 2BR Dago Point', city:'Bandung, Jawa Barat', land:0, build:58, beds:2, price:890000000, desc:'Unit lantai tinggi dengan pemandangan kota, dekat kampus dan kawasan kuliner Dago.'},
  {id:10, mode:'lelang', type:'Rumah', title:'Rumah Hook Perumahan Puri Anjasmoro', city:'Semarang, Jawa Tengah', land:150, build:130, beds:3, price:1350000000, bid:1180000000, bidders:11, duration: 83, desc:'Rumah hook dua muka jalan, lokasi dekat tol Krapyak. Lelang atas permintaan kreditur.'},
  {id:11, mode:'langsung', type:'Tanah', title:'Tanah Pinggir Jalan Raya Jogja-Solo', city:'Klaten, Jawa Tengah', land:800, build:0, beds:0, price:1600000000, desc:'Cocok untuk usaha SPBU, showroom, atau gudang distribusi. Lebar depan 24 meter.'},
  {id:12, mode:'lelang', type:'Villa', title:'Villa Kolam Renang Canggu', city:'Canggu, Bali', land:250, build:140, beds:2, price:5200000000, bid:4750000000, bidders:8, duration: 6, desc:'Villa modern dekat pantai Canggu, kolam renang privat, populer untuk sewa jangka pendek.'},
  {id:13, mode:'langsung', type:'Ruko', title:'Ruko Baru Perumahan Citraland', city:'Surabaya, Jawa Timur', land:80, build:160, beds:0, price:1750000000, desc:'Ruko dua lantai siap pakai, dalam kawasan komersial yang sudah ramai penghuni.'},
  {id:14, mode:'terjual', type:'Tanah', title:'Kavling Industri Driyorejo', city:'Gresik, Jawa Timur', land:2000, build:0, beds:0, price:3100000000, desc:'Kavling kawasan industri, sudah terjual pada sesi lelang sebelumnya.'},
  {id:15, mode:'lelang', type:'Rumah', title:'Rumah Asri Komplek Tidar', city:'Malang, Jawa Timur', land:140, build:110, beds:3, price:1050000000, bid:960000000, bidders:7, duration: 64, desc:'Rumah dengan taman depan luas, lingkungan tenang dekat kampus ITN Malang.'},
  {id:16, mode:'langsung', type:'Apartemen', title:'Apartemen Tower Pakuwon Mall', city:'Surabaya, Jawa Timur', land:0, build:45, beds:1, price:610000000, desc:'Unit terhubung langsung ke mall dan kampus, ideal untuk investasi sewa mahasiswa.'}
];

export const propertyTypes = ["Rumah", "Tanah", "Apartemen", "Ruko", "Gudang", "Villa"];
