import { NextResponse } from "next/server";
import { and, asc, eq, ilike, or, sql } from "drizzle-orm";
import { getAuthenticatedActor, requireRole } from "@/server/auth/actor";
import { apiErrorResponse } from "@/server/api";
import { getDatabase } from "@/server/db/client";
import { profiles, userRoles } from "@/server/db/schema";
import { adminPage, adminPageResult } from "@/server/admin-pagination";

export const runtime="nodejs"; export const dynamic="force-dynamic";
export async function GET(request:Request){try{requireRole(await getAuthenticatedActor(),"admin");const parameters=new URL(request.url).searchParams;const database=getDatabase();if(parameters.get("page")!=="1"){const data=await database.select({id:profiles.id,email:profiles.email,name:profiles.name,status:profiles.status,role:userRoles.role,createdAt:profiles.createdAt}).from(profiles).leftJoin(userRoles,eq(userRoles.userId,profiles.id)).orderBy(asc(profiles.email));return NextResponse.json({data},{headers:{"Cache-Control":"no-store"}});}const page=adminPage(parameters);const condition=and(page.q?or(ilike(profiles.email,"%"+page.q+"%"),ilike(profiles.name,"%"+page.q+"%")):undefined,page.status?eq(profiles.status,page.status as typeof profiles.status.enumValues[number]):undefined);const base=database.select({id:profiles.id,email:profiles.email,name:profiles.name,status:profiles.status,createdAt:profiles.createdAt}).from(profiles).where(condition).orderBy(asc(profiles.email),asc(profiles.id)).limit(page.limit+1).offset(page.offset);const profileRows=await base;const ids=profileRows.slice(0,page.limit).map((row)=>row.id);const roles=ids.length?await database.select().from(userRoles).where(sql`${userRoles.userId} in ${ids}`):[];const roleMap=new Map<string,string[]>();for(const role of roles)roleMap.set(role.userId,[...(roleMap.get(role.userId)||[]),role.role]);const[count]=await database.select({value:sql<number>`count(*)::integer`}).from(profiles).where(condition);const items=profileRows.map((row)=>({...row,roles:roleMap.get(row.id)||[]}));return NextResponse.json({data:adminPageResult(items,page.limit,page.offset,count.value)},{headers:{"Cache-Control":"no-store"}});}catch(error){return apiErrorResponse(error);}}
