"use client";
import { useEffect, useState } from "react";
import { apiRequest } from "@/components/api-client";
import { csrfHeaders } from "@/components/csrf";
import { StatusBadge } from "@/components/status-badge";
import styles from "../dashboard-shell.module.css";
type Lead={id:string;name:string;email?:string;phone?:string;message?:string;status:string;createdAt:string};
type Contact={email?:string;phone?:string};
// Kontak yang dikirim server sudah tersamar (mis. "bud***com"); nilai asli hanya didapat lewat
// POST .../contact per lead, dan dicatat di audit log (lead.contact.viewed).
export default function LeadsPage(){const[items,setItems]=useState<Lead[]>([]);const[error,setError]=useState("");const[revealed,setRevealed]=useState<Record<string,Contact>>({});const[revealing,setRevealing]=useState<string|null>(null);async function load(){try{setItems(await apiRequest<Lead[]>("/api/v1/leads/admin",{cache:"no-store"}));}catch(reason){setError(reason instanceof Error?reason.message:"Gagal memuat lead.");}}useEffect(()=>{const controller=new AbortController();apiRequest<Lead[]>("/api/v1/leads/admin",{cache:"no-store",signal:controller.signal}).then((data)=>{if(!controller.signal.aborted)setItems(data);}).catch((reason)=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Gagal memuat lead.");});return()=>controller.abort();},[]);async function update(id:string,status:string){try{await apiRequest("/api/v1/leads/admin/"+id,{method:"PATCH",headers:{"Content-Type":"application/json",...await csrfHeaders()},body:JSON.stringify({status})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Gagal mengubah lead.");}}async function reveal(id:string){setRevealing(id);try{const data=await apiRequest<Contact>("/api/v1/leads/admin/"+id+"/contact",{method:"POST",headers:await csrfHeaders()});setRevealed((prior)=>({...prior,[id]:data}));}catch(reason){setError(reason instanceof Error?reason.message:"Gagal menampilkan kontak.");}finally{setRevealing(null);}}return <><div className={styles.heading}><div><h1>Lead</h1><p>Riwayat minat Anda dan tindak lanjut listing.</p></div></div><section className={styles.panel}>{error&&<p className={styles.error}>{error}</p>}{items.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Kontak</th><th>Pesan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{items.map((item)=>{const contact=revealed[item.id];return <tr key={item.id}><td data-label="Kontak"><strong>{item.name}</strong><br/><small>{contact?contact.email||"—":item.email||"—"} · {contact?contact.phone||"—":item.phone||"—"}</small>{!contact&&<><br/><button type="button" className={styles.btn} onClick={()=>void reveal(item.id)} disabled={revealing===item.id}>{revealing===item.id?"Memuat…":"Tampilkan kontak"}</button></>}</td><td data-label="Pesan">{item.message||"—"}</td><td data-label="Status"><StatusBadge kind="lead" value={item.status}/></td><td><div className={styles.actions}>{["new","contacted","closed","spam"].map((status)=><button key={status} disabled={status===item.status} onClick={()=>void update(item.id,status)}>{status}</button>)}</div></td></tr>;})}</tbody></table></div>:<p className={styles.empty}>Belum ada lead.</p>}</section></>}
