"use client";
import { useEffect, useState } from "react";
import { apiRequest } from "@/components/api-client";
import { csrfHeaders } from "@/components/csrf";
import { StatusBadge } from "@/components/status-badge";
import styles from "../dashboard-shell.module.css";
type Lead={id:string;name:string;email?:string;phone?:string;message?:string;status:string;createdAt:string};
const mask=(value?:string)=>!value?"—":value.length<7?value.slice(0,2)+"***":value.slice(0,3)+"***"+value.slice(-3);
export default function LeadsPage(){const[items,setItems]=useState<Lead[]>([]);const[error,setError]=useState("");async function load(){try{setItems(await apiRequest<Lead[]>("/api/v1/leads/admin",{cache:"no-store"}));}catch(reason){setError(reason instanceof Error?reason.message:"Gagal memuat lead.");}}useEffect(()=>{const controller=new AbortController();apiRequest<Lead[]>("/api/v1/leads/admin",{cache:"no-store",signal:controller.signal}).then((data)=>{if(!controller.signal.aborted)setItems(data);}).catch((reason)=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Gagal memuat lead.");});return()=>controller.abort();},[]);async function update(id:string,status:string){try{await apiRequest("/api/v1/leads/admin/"+id,{method:"PATCH",headers:{"Content-Type":"application/json",...await csrfHeaders()},body:JSON.stringify({status})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Gagal mengubah lead.");}}return <><div className={styles.heading}><div><h1>Lead</h1><p>Riwayat minat Anda dan tindak lanjut listing.</p></div></div><section className={styles.panel}>{error&&<p className={styles.error}>{error}</p>}{items.length?<table className={styles.table}><thead><tr><th>Kontak</th><th>Pesan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{items.map((item)=><tr key={item.id}><td><strong>{item.name}</strong><br/><small>{mask(item.email)} · {mask(item.phone)}</small></td><td>{item.message||"—"}</td><td><StatusBadge kind="lead" value={item.status}/></td><td><div className={styles.actions}>{["new","contacted","closed","spam"].map((status)=><button key={status} disabled={status===item.status} onClick={()=>void update(item.id,status)}>{status}</button>)}</div></td></tr>)}</tbody></table>:<p className={styles.empty}>Belum ada lead.</p>}</section></>}
