"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiRequest, ApiClientError } from "@/components/api-client";
import { csrfHeaders } from "@/components/csrf";
import { StatusBadge } from "@/components/status-badge";
import { formatRupiah } from "@/lib/currency";
import styles from "../dashboard-shell.module.css";

type Item={id:string;title:string;type:string;askingPrice:number;version:number;publicationStatus:string;latestRevisionStatus:string;updatedAt:string;location:{city:string;province:string}|null};
const statuses=["","draft","pending_review","revision_required","published","paused","rejected","archived"];
export default function PropertiesPage(){
 const[items,setItems]=useState<Item[]>([]);const[selected,setSelected]=useState<string[]>([]);const[q,setQ]=useState("");const[status,setStatus]=useState("");const[bulkStatus,setBulkStatus]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const params=new URLSearchParams();if(q.trim())params.set("q",q.trim());if(status)params.set("status",status);setItems(await apiRequest<Item[]>("/api/v1/admin/properties?"+params.toString(),{cache:"no-store"}));setSelected([]);}catch(reason){setError(reason instanceof ApiClientError?reason.message:"Gagal memuat properti.");}finally{setLoading(false);}},[q,status]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timer);},[load]);
 const allSelected=items.length>0&&items.every(item=>selected.includes(item.id));
 function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);}
 async function updateStatus(ids:string[],nextStatus:string){if(!ids.length||!nextStatus||!window.confirm("Ubah status "+ids.length+" properti menjadi "+nextStatus+"?"))return;try{await apiRequest("/api/v1/admin/properties",{method:"PATCH",headers:{"Content-Type":"application/json",...await csrfHeaders()},body:JSON.stringify({ids,status:nextStatus})});setNotice(ids.length+" properti diubah ke status "+nextStatus+".");setBulkStatus("");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Gagal mengubah status properti.");}}
 return <><div className={styles.heading}><div><h1>Properti</h1><p>Draft, revisi, dan status publikasi dari PostgreSQL.</p></div><Link className="button dark" href="/dashboard/properties/new">Tambah properti</Link></div><section className={styles.panel}><div className={styles.actions}><label>Cari <input type="search" value={q} onChange={event=>setQ(event.target.value)} placeholder="Judul properti" /></label><label>Status <select value={status} onChange={event=>setStatus(event.target.value)}>{statuses.map(value=><option key={value} value={value}>{value||"Semua status"}</option>)}</select></label>{selected.length>0&&<><select aria-label="Status baru" value={bulkStatus} onChange={event=>setBulkStatus(event.target.value)}><option value="">Pilih status</option>{statuses.filter(Boolean).map(value=><option key={value}>{value}</option>)}</select><button type="button" disabled={!bulkStatus} onClick={()=>void updateStatus(selected,bulkStatus)}>Ubah status ({selected.length})</button></>}</div>{error&&<p className={styles.error}>{error}</p>}{notice&&<p role="status" className={styles.notice}>{notice}</p>}{loading?<p>Memuat…</p>:items.length?<table className={styles.table}><thead><tr><th><input aria-label="Pilih semua" type="checkbox" checked={allSelected} onChange={event=>setSelected(event.target.checked?items.map(item=>item.id):[])} /></th><th>Properti</th><th>Status</th><th>Harga</th><th>Versi</th><th>Aksi</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><input aria-label={"Pilih "+item.title} type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggle(item.id)} /></td><td><strong>{item.title}</strong><br/><small>{item.location?.city}, {item.location?.province} · {item.type}</small></td><td><StatusBadge kind="publication" value={item.publicationStatus}/><br/><small>Revisi: {item.latestRevisionStatus}</small></td><td>{formatRupiah(item.askingPrice)}</td><td>v{item.version}</td><td><div className={styles.actions}><Link href={"/dashboard/properties/"+item.id}>Buka editor</Link><button type="button" onClick={()=>void updateStatus([item.id],"archived")}>Arsipkan</button></div></td></tr>)}</tbody></table>:<p className={styles.empty}>Belum ada properti.</p>}</section></>;
}
