GRANT CONNECT ON DATABASE lelang_properti_dev TO lelang_app;
GRANT USAGE ON SCHEMA app TO lelang_app;
GRANT SELECT ON ALL TABLES IN SCHEMA app TO lelang_app;
GRANT UPDATE (updated_at, email_verified_at) ON app.profiles TO lelang_app;
GRANT INSERT, UPDATE, DELETE ON app.properties, app.property_revisions, app.property_media, app.leads, app.outbox_events, app.user_sessions, app.auth_rate_limits TO lelang_app;
GRANT INSERT ON app.user_identities TO lelang_app;
GRANT INSERT, DELETE ON app.oauth_transactions TO lelang_app;
GRANT INSERT ON app.audit_logs TO lelang_app;
REVOKE UPDATE, DELETE, TRUNCATE ON app.audit_logs FROM lelang_app;
REVOKE CREATE ON SCHEMA app FROM lelang_app;
